### ISSUE TITLE
Can't connect to server with `wake lsp --port <PORT>`

### ISSUE THREAD

**Issue by zeroaddresss** [Ackee-Blockchain/tools-for-solidity-vscode#100]
After installing the extension, it fails to connect to server. I have made some trivial attempts like uninstalling, restarting VSCode and checking my ports (no other process was running on that specific port).
Thanks in advance if you can help me figure this out

Leaving the output below:
```
Running 'wake lsp --port <PORT>' (v4.10.1)
Timed out waiting for port 58619 to open.
[Error - 11:26:07] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 11:26:07] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Info  - 11:26:07] Connection to server got closed. Server will restart.
[Error - 11:26:07] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:26:07] Tools for Solidity client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:26:07] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:26:07] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:26:33] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 11:26:33] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 11:26:33] Stopping server failed
Error: Previous start failed. Can't restart server.
	at E.$start (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704292)
	at E.shutdown (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701363)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701138)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:860069)
	at E.handleConnectionError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:706716)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:705543
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704709
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:648573
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at g.fireError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:668212)
	at Socket.<anonymous> (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:668998)
	at Socket.emit (node:events:529:35)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Error - 11:26:33] Stopping server failed
Error: Previous start failed. Can't restart server.
	at E.$start (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704292)
	at E.shutdown (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701363)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701138)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:860069)
	at E.handleConnectionError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:706716)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:705543
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704709
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:648508
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at m.fireError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:664686)
	at Socket.<anonymous> (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:666292)
	at Socket.emit (node:events:529:35)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Info  - 11:26:33] Connection to server got closed. Server will restart.
[Error - 11:26:33] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:26:33] Tools for Solidity client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:26:59] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 11:26:59] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 11:26:59] Stopping server failed
Error: Previous start failed. Can't restart server.
	at E.$start (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704292)
	at E.shutdown (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701363)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701138)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:860069)
	at E.handleConnectionError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:706716)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:705543
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704709
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:648573
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at g.fireError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:668212)
	at Socket.<anonymous> (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:668998)
	at Socket.emit (node:events:529:35)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Error - 11:26:59] Stopping server failed
Error: Previous start failed. Can't restart server.
	at E.$start (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704292)
	at E.shutdown (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701363)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701138)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:860069)
	at E.handleConnectionError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:706716)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:705543
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704709
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:648508
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at m.fireError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:664686)
	at Socket.<anonymous> (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:666292)
	at Socket.emit (node:events:529:35)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Info  - 11:26:59] Connection to server got closed. Server will restart.
[Error - 11:26:59] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:26:59] Tools for Solidity client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:26:59] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:27:25] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 11:27:25] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 11:27:25] Stopping server failed
Error: Previous start failed. Can't restart server.
	at E.$start (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704292)
	at E.shutdown (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701363)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701138)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:860069)
	at E.handleConnectionError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:706716)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:705543
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704709
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:648573
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at g.fireError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:668212)
	at Socket.<anonymous> (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:668998)
	at Socket.emit (node:events:529:35)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Error - 11:27:25] Stopping server failed
Error: Previous start failed. Can't restart server.
	at E.$start (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704292)
	at E.shutdown (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701363)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701138)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:860069)
	at E.handleConnectionError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:706716)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:705543
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704709
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:648508
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at m.fireError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:664686)
	at Socket.<anonymous> (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:666292)
	at Socket.emit (node:events:529:35)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Info  - 11:27:25] Connection to server got closed. Server will restart.
[Error - 11:27:25] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:27:25] Tools for Solidity client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:27:25] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:27:51] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 11:27:51] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 11:27:51] Stopping server failed
Error: Previous start failed. Can't restart server.
	at E.$start (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704292)
	at E.shutdown (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701363)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701138)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:860069)
	at E.handleConnectionError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:706716)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:705543
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704709
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:648573
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at g.fireError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:668212)
	at Socket.<anonymous> (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:668998)
	at Socket.emit (node:events:529:35)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Error - 11:27:51] Stopping server failed
Error: Previous start failed. Can't restart server.
	at E.$start (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704292)
	at E.shutdown (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701363)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701138)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:860069)
	at E.handleConnectionError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:706716)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:705543
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704709
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:648508
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at m.fireError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:664686)
	at Socket.<anonymous> (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:666292)
	at Socket.emit (node:events:529:35)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Info  - 11:27:51] Connection to server got closed. Server will restart.
[Error - 11:27:51] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:27:51] Tools for Solidity client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:27:51] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:28:17] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 11:28:17] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 11:28:17] Stopping server failed
Error: Previous start failed. Can't restart server.
	at E.$start (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704292)
	at E.shutdown (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701363)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701138)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:860069)
	at E.handleConnectionError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:706716)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:705543
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704709
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:648573
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at g.fireError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:668212)
	at Socket.<anonymous> (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:668998)
	at Socket.emit (node:events:529:35)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Error - 11:28:17] Stopping server failed
Error: Previous start failed. Can't restart server.
	at E.$start (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704292)
	at E.shutdown (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701363)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:701138)
	at E.stop (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:860069)
	at E.handleConnectionError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:706716)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:705543
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:704709
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at /Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:648508
	at i.invoke (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656198)
	at o.fire (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:656963)
	at m.fireError (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:664686)
	at Socket.<anonymous> (/Users/asdrubale/.vscode-oss/extensions/ackeeblockchain.tools-for-solidity-1.14.0/dist/extension.js:2:666292)
	at Socket.emit (node:events:529:35)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Error - 11:28:17] The Tools for Solidity server crashed 6 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 11:28:17] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:28:17] Tools for Solidity client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 11:28:17] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

**Comment by michprev** [comment]
Hey @zeroaddresss, is this issue bound to any specific codebase, or does this happen with any Solidity project?

Can you try to run the command `wake lsp --port <PORT>` on a command line and set the port in the Tools for Solidity settings (`Tools-for-Solidity.Wake.port`)?

**Comment by zeroaddresss** [comment]
> Hey @zeroaddresss, is this issue bound to any specific codebase, or does this happen with any Solidity project?
> 
> Can you try to run the command `wake lsp --port <PORT>` on a command line and set the port in the Tools for Solidity settings (`Tools-for-Solidity.Wake.port`)?

The issue happens on any codebase, and I've tried waking the port from terminal and setting that specific port in the extension settings, but I'm still getting the same output for the extension (timeout).
Let me know if there's something else I can do to help you debug this
