### ISSUE TITLE
Tools for Solidity crashes every time I install/enable it

### ISSUE THREAD

**Issue by smbsp** [Ackee-Blockchain/tools-for-solidity-vscode#59]
I am facing this issue every time. Can I get some help here?

`Running 'woke lsp --port 57354'
[Error - 22:44:23] Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/woke/lsp/server.py", line 268, in _task_done_callback
    task.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/woke/lsp/lsp_compiler.py", line 187, in run
    await self.__compilation_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/woke/lsp/lsp_compiler.py", line 936, in __compilation_loop
    await self.__compile(self.__discovered_files)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/woke/lsp/lsp_compiler.py", line 567, in __compile
    for version in reversed(self.__svm.list_all())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/woke/svm/svm.py", line 182, in list_all
    self.__fetch_list_file()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/woke/svm/svm.py", line 247, in __fetch_list_file
    with urllib.request.urlopen(self.__solc_list_url, timeout=0.25) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

[Error - 22:44:23] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 22:44:23] Client Tools for Solidity: connection to server is erroring. Shutting down server.
[Error - 22:44:23] Connection to server got closed. Server will not be restarted.
[Error - 22:44:23] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 22:44:23] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 22:44:23] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
`

**Comment by michprev** [comment]
Hi @smbsp,
can you please try to follow this recommendation? https://github.com/Ackee-Blockchain/tools-for-solidity-vscode/issues/44#issuecomment-1441631192

**Comment by smbsp** [comment]
This worked. Thanks!
