### ISSUE TITLE
[Bug] The Tools for Solidity server crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by marchev** [Ackee-Blockchain/tools-for-solidity-vscode#63]
Hi!

I get the output when I try to use in the following Foundry project: https://github.com/code-423n4/2023-09-maia

```sh
Running 'woke lsp --port 61030'
[Error - 14:35:40] Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/woke/lsp/server.py", line 268, in _task_done_callback
    task.result()
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/compiler.py", line 1130, in compile_unit_raw
    return await self.__solc_frontend.compile(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/solc_frontend/solc_runner.py", line 55, in compile
    return await self.__run_solc(target_version, standard_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/solc_frontend/solc_runner.py", line 62, in __run_solc
    raise SolcCompilationError(
woke.compiler.solc_frontend.exceptions.SolcCompilationError: solc version `0.8.20` is not installed.

[Error - 14:35:40] solc version `0.8.20` is not installed.
[Info  - 14:35:40] Connection to server got closed. Server will restart.
[Error - 14:35:41] Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/woke/lsp/server.py", line 268, in _task_done_callback
    task.result()
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/compiler.py", line 1130, in compile_unit_raw
    return await self.__solc_frontend.compile(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/solc_frontend/solc_runner.py", line 55, in compile
    return await self.__run_solc(target_version, standard_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/solc_frontend/solc_runner.py", line 62, in __run_solc
    raise SolcCompilationError(
woke.compiler.solc_frontend.exceptions.SolcCompilationError: solc version `0.8.20` is not installed.

[Error - 14:35:41] solc version `0.8.20` is not installed.
[Info  - 14:35:41] Connection to server got closed. Server will restart.
[Error - 14:35:41] Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/woke/lsp/server.py", line 268, in _task_done_callback
    task.result()
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/compiler.py", line 1130, in compile_unit_raw
    return await self.__solc_frontend.compile(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/solc_frontend/solc_runner.py", line 55, in compile
    return await self.__run_solc(target_version, standard_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/solc_frontend/solc_runner.py", line 62, in __run_solc
    raise SolcCompilationError(
woke.compiler.solc_frontend.exceptions.SolcCompilationError: solc version `0.8.20` is not installed.

[Error - 14:35:41] solc version `0.8.20` is not installed.
[Info  - 14:35:41] Connection to server got closed. Server will restart.
[Error - 14:35:42] Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/woke/lsp/server.py", line 268, in _task_done_callback
    task.result()
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/compiler.py", line 1130, in compile_unit_raw
    return await self.__solc_frontend.compile(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/solc_frontend/solc_runner.py", line 55, in compile
    return await self.__run_solc(target_version, standard_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/solc_frontend/solc_runner.py", line 62, in __run_solc
    raise SolcCompilationError(
woke.compiler.solc_frontend.exceptions.SolcCompilationError: solc version `0.8.20` is not installed.

[Error - 14:35:42] solc version `0.8.20` is not installed.
[Info  - 14:35:42] Connection to server got closed. Server will restart.
[Error - 14:35:42] Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/woke/lsp/server.py", line 268, in _task_done_callback
    task.result()
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/compiler.py", line 1130, in compile_unit_raw
    return await self.__solc_frontend.compile(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/solc_frontend/solc_runner.py", line 55, in compile
    return await self.__run_solc(target_version, standard_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/woke/compiler/solc_frontend/solc_runner.py", line 62, in __run_solc
    raise SolcCompilationError(
woke.compiler.solc_frontend.exceptions.SolcCompilationError: solc version `0.8.20` is not installed.

[Error - 14:35:42] solc version `0.8.20` is not installed.
[Error - 14:35:42] The Tools for Solidity server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

I checked in `~/.local/share/woke/compilers` but there is a 0.8.20 solc there:

```sh
~/.local/share/woke/compilers
❯ ls -lah
total 104
drwxr-xr-x  5 anon  staff   160B Sep 28 14:36 .
drwxr-xr-x  3 anon  staff    96B Sep 28 14:32 ..
drwxr-xr-x  3 anon  staff    96B Sep 28 14:36 solc-macosx-amd64-v0.8.19+commit.7dd6d404
drwxr-xr-x  3 anon  staff    96B Sep 28 14:32 solc-macosx-amd64-v0.8.20+commit.a1b79de6
-rw-r--r--  1 anon  staff    50K Sep 28 14:36 solc.json
```

Am I doing something wrong or is that an actual bug?

**Comment by marchev** [comment]
I resolved the issue thanks to the good fellas at the Woke: Unofficial Telegram group.

To fix the issue, run this command:
```sh
woke svm install --force 0.8.20
```
